/login
이메일, 비밀번호

/signup
이메일, 비밀번호, 이름, 학교명

/create-channel (채널 생성하기)
학교 이름, 학교구조도 이미지 파일 선택

/school-channel (학교 채널 메인화면)
해당 채널의 방 코드를 프론트에 전달해서 띄워야함
그리고 만약 새 코드 생성 버튼을 누르면 백에서 재생성해야 함

/scenario (시나리오 관리 화면)
db에 시나리오 테이블 관련 컬럼들 수정 및 조회해야함

